trigger:
  - main

variables:
  vmImageName: "windows-latest"
  projectName: "SampleApp"
  

stages:
  - stage: Build
    displayName: Build Ionic - Android projects
    jobs:
      # Debug build
      - job: Build_Ionic_Android_Debug
        variables:
          - name: buildConfiguration
            value: Debug
        displayName: Build Debug
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: ionic-android-debug-build.yml
          - task: Cache@2
            inputs:
              key: 'package-lock.json'
              path: '$(npm_config_cache)'
          
          - script: |
              npm ci --cache $(npm_config_cache)
            displayName: NPM Install Dependencies

      # # Release build
      # - job: Build_Ionic_Android_Release
      #   variables:
      #     - name: buildConfiguration
      #       value: Release
      #   displayName: Build Release
      #   pool:
      #     vmImage: $(vmImageName)
      #   steps:
      #     - template: ionic-android-release-build.yml
