trigger:
  - main

variables:
  vmImageName: "windows-latest"
  projectName: "azureIonic"

stages:
  - stage: Build
    displayName: Build Ionic - Android projects
    jobs:
      - job: Build_Ionic_Android_Debug
        variables:
          - name: buildConfiguration
            value: Debug
        displayName: Build Debug
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Write your commands here
                
                echo Hello world
